# -----------------------------------------------
#   DragonProxy Configuration (05/08/19)
#   https://github.com/DragonetMC/DragonProxy
# -----------------------------------------------

locale: 'EN'

# The IP and port the proxy will listen for connections on
# '0.0.0.0' will bind to all IP addresses available on your device
bind-address: '0.0.0.0'
bind-port: 19132

# The MOTD that will be shown on the MCPE server list
motd: 'DragonProxy'
motd2: 'https://github.com/DragonetMC/DragonProxy'

# The maximum amount of players that can join the proxy
max-players: 1

# The IP and port of the remote server to connect to
# TODO: Add support for multiple servers
remote-address: 'mc.hypixel.net'
remote-port: 25565

# TODO
#remote-servers:
#  local:
#    address: '127.0.0.1'
#    port: 25566
#    default: true

# The authentication method used for connecting to the remote server.
# Accepted values:
#   credentials   : This will display a form when you join the proxy asking you to enter your Mojang credentials
#   offline       : No authentication, cant join premium servers such as Hypixel
remote-auth: credentials

# Whether or not Bedrock clients should be authenticated with xbox live
xbox-auth: false

# Whether or not to use the motd and player count of the primary remote server
ping-passthrough: true

# Whether or not to fetch skins from Mojang's servers
fetch-player-skins: true

# The amount of threads that will be used.
# Only change if you know what you are doing
thread-pool-size: 8
