# =================================
#| DragonProxy Configuration File  |
#|       A BytePowered Team        |
# =================================
# https://GitHub.com/DragonetMC/DragonProxy/wiki

# Language file
# Default = English
lang: default


# What IP and port to bind on your own computer/server. 
# IP 0.0.0.0 means bind to all IP addresses available on your own computer/server.
udp_bind_ip: '0.0.0.0'
udp_bind_port: 19132


# The MOTD (Message of the Day) that will be shown on the MCPE Server List
motd: '&aServer by DragonProxy'


# What server should we connect to by default?
# Set the server nams in the next option
default_server: 'my_pc_server'


# A list of remote servers
# Notice: Please use spaces instead of TABs as indentions
remote_servers:
  my_pc_server:
    # Next line indicates this is a Desktop(PC/Mac) server. 
    !!org.dragonet.proxy.DesktopServer
    remote_addr: '127.0.0.1'
    remote_port: 25565
  my_pe_server:
    # Next line indicates this is a Pocket Edition server. 
    !!org.dragonet.proxy.PocketServer
    remote_addr: 'your.packets.server.com'
    remote_port: 19132


# Server Authentication Modes
# cls     : Use Dragonet CLS (central login system) @ http://auth.dragonet.org
#           Dragonet CLS will authenticate Minecraft accounts automatically
#           so you don't have to type in password again and again. 
# online  : Traditional login screen by DragonProxy, BUGGY.
# offline : Run the server in offline mode so you can't join premium 
#           servers like Hypixel. 
mode: cls


# The in-game command prefix for players, by default it's Minecraft command prefix (a slash).
command_prefix: '/'


# How many players can join the proxy at once?
# Set to -1 for infinite
max_players: -1


# Should we save console text in a file?
log_console: true


# How many threads will process MCPE packets? Only change if you know what you're doing.
# Recommanded at least 8 threads. 
# If you using this software at home, you can set to lower value like 8 or 12.  
thread_pool_size: 16
